channels:
- conda-forge
- esri
dependencies:
# Jupyter
- jupyterlab>=3
- jupyterlab_launcher
- jupyter_dashboards
- nodejs
- nbconvert
- widgetsnbextension
- voila
# Python Kernel
- pillow
- python
- pyarrow
- pandas
- arcgis
- geopandas
- shapely
- fiona
- ipykernel
- ipywidgets
- matplotlib
- seaborn
- pyyaml
- traittypes
- traitlets
- vdom
- invoke
