name: minimal-iges-binder-environment

channels:
  - conda-forge

dependencies:
  - python=3.9
  - numpy
  - pandas
  - jupyterlab
  - jupyterlab_launcher
  - jupyter_dashboards
  - jupyterlab_widgets
  - ipywidgets
  - nodejs
  - nbconvert
  - widgetsnbextension
  - ipykernel
  - plotly
  - voila
  - pytorch
  - pytorch-lightning
  - scikit-learn
  - pip
  - pip:
    - geopy
    - haversine
    - cartopy
    - cdsapi
    - eccodes
    - geopandas
    - shapely
    - fiona
    - pillow
    - pyarrow
    - sqlalchemy
    - openpyxl
    - matplotlib
    - seaborn
    - pyyaml
    - traittypes
    - traitlets
    - vdom
    - invoke
