channels:
- conda-forge
- esri
dependencies:
# Jupyter
- jupyterlab=2
- nodejs=10.13
- nbconvert=6
- widgetsnbextension=3.5
# Python Kernel
- python=3.7
- pandas=1.1.2
- arcgis=1.8.2
- geopandas=0.6.1
- ipykernel=5.3.4
- ipywidgets=7.5.1
- ipyleaflet=0.13.1
- matplotlib=3.3.1
- seaborn=0.11
- pyyaml=5.3.1
- traittypes=0.2.1
- invoke=1.4.1
