name: iges-binder-environment

channels:
  - conda-forge
  - esri
dependencies:
  - jupyterlab=2
  - jupyterlab_launcher
  - jupyter_dashboards
  - nodejs
  - nbconvert
  - widgetsnbextension
  - plotly
  - voila
  - pandas
  - numpy
  - arcgis
  - geopandas
  - shapely
  - fiona
  - pillow
  - pyarrow
  - sqlalchemy
  - ipykernel
  - ipywidgets
  - matplotlib
  - seaborn
  - pyyaml
  - traittypes
  - traitlets
  - vdom
  - invoke
