name: iges-binder-environment

channels:
  - conda-forge
  #- esri
dependencies:
  - jupyterlab
  - jupyterlab_launcher
  - jupyter_dashboards
  - jupyterlab_widgets
  - nodejs
  - nbconvert
  - widgetsnbextension
  - plotly
  - voila
  - pandas
  - numpy
  - geopy
  - haversine
  - cartopy
  - cdsapi
  - eccodes
  - torch
  - pytorch
  - pytorch_lightning
  - ecmwflibs
  - scikit-learn
  #- arcgis
  - geopandas
  - shapely
  - fiona
  - pillow
  - pyarrow
  - sqlalchemy
  - openpyxl
  - ipykernel
  - ipywidgets
  - matplotlib
  - seaborn
  - pyyaml
  - traittypes
  - traitlets
  - vdom
  - invoke
