channels:
- conda-forge
- esri
dependencies:
# Jupyter
- jupyterlab=2
- jupyter_dashboards
- nodejs=10.13
- nbconvert=6
- widgetsnbextension=3.5
- voila
# Python Kernel
- python=3.8
- pandas=1.1
- arcgis=1.8.2
- geopandas=0.6.1
- shapely=1.6.4
- fiona=1.8
- ipykernel=5.3.4
- ipywidgets=7.5.1
- ipyleaflet=0.12
- matplotlib=3.3.1
- seaborn=0.11
- pyyaml=5.3.1
- traittypes==0.2.1
- invoke=1.4.1
